# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-16 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20170216_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255), unique=True),
        ),
    ]
